### ISSUE TITLE
Охо, я похоже догадалась. 

### ISSUE THREAD

**Issue by Satorisan** [lockedshadow/gensokyo-no-tegami#1]
Я ведь не настолько бака, верно? И не смотри, что я немного под другой личностью. Это нормально.

**Comment by RedKsiadz** [comment]
Молодец же.

**Comment by lockedshadow** [comment]
Да, всё правильно!  И вовсе ты не бака, это скорее я всё усложняю на ровном месте.

**Comment by Satorisan** [comment]
Эт точно. Собственно почему мне был нужен этот канал — есть борда. Ее создатель немного забросил. Но пароль от админки у меня остался.  http://zenchan.hk/Flanchan/
Может стать резервным каналом. Увы, от хостинга у меня пароля нету. Но сайт работает уже больше года, так что вряд ли его отключат. Отдельную доску, которая не выводится во фрейме я создала. Ну, как-то так.

**Comment by RedKsiadz** [comment]
Фланя, ты молодец же.

**Comment by Satorisan** [comment]
^_^

**Comment by lockedshadow** [comment]
Мне кажется, это просто отличный вариант.  Особенно если он окажется достаточно долговечным. Домен, правда, продлён только до июня, но за это время точно можно будет что-то придумать в более спокойной обстановке, если в этом ещё будет необходимость. Так значит, перемещаемся?

**Comment by Satorisan** [comment]
Да. В крайнем случае есть субдомен, по которому можно попасть на сайт. Но я думаю, домен можно продлить, так как подозреваю, какой пароль от почты, на который его регистрировали. И вообще, он может стоят на автпродлении. Другое дело, что домены сейчас подорожали в два раза почти.  Но это детали.
